/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fanfan' at '2/17/17 1:41 PM' with Gradle 2.9
 *
 * @author fanfan, @date 2/17/17 1:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
